"""Derive a fetchable corpus manifest from the papers on disk.

Resolves the reproducibility problem stated at the top of eval/corpus.yaml.
Ground truth is being written against a local literature review, because
labelling quality is bounded by the labeller's knowledge of the papers — but
those PDFs cannot be redistributed, so without this nobody could reproduce the
ablation table.

Most of that corpus is open access. This finds each paper's public identifier
and writes a manifest that `fetch_corpus.py` can rebuild the corpus from, so
the labels stay attached to papers a stranger can obtain.

    python scripts/build_corpus.py > eval/corpus.generated.yaml

Identifiers are read from the PDF text and the filename, never invented. A
paper whose identifier cannot be found is emitted with a `needs:` marker rather
than a guess, because a wrong DOI in a manifest is worse than an absent one —
it sends a reader to a different paper and looks authoritative doing it.
"""

from __future__ import annotations

import re
import sys
import warnings
from pathlib import Path

warnings.filterwarnings("ignore")
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from researchlens.ingest.library import load_library  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

ARXIV = re.compile(r"(?:arxiv[:\s]*)?(\d{4}\.\d{4,5})(?:v\d+)?", re.I)
DOI = re.compile(r"\b(10\.\d{4,9}[/:][-._;()/:A-Za-z0-9]+)", re.I)
BIORXIV = re.compile(r"biorxiv[^\d]{0,20}(\d{6,7})", re.I)


def _identify(doc, path: Path) -> tuple[str, str] | None:
    """Return (scheme, id) from the paper's text or its filename."""
    if doc is not None and doc.arxiv_id:
        return ("arxiv", doc.arxiv_id)

    haystacks = [path.name]
    if doc is not None:
        # Only the front matter: a DOI in the reference list belongs to a
        # different paper, and picking one up there is exactly the silent
        # wrong-identifier failure this avoids.
        haystacks.append(" ".join(s.text for s in doc.sections[:2])[:2500])

    for hay in haystacks:
        m = ARXIV.search(hay)
        if m:
            return ("arxiv", m.group(1))
        m = DOI.search(hay)
        if m:
            return ("doi", m.group(1).rstrip(".,;"))
        m = BIORXIV.search(hay)
        if m:
            return ("biorxiv", m.group(1))
    return None


def main() -> None:
    docs, _ = load_library(ROOT / "data" / "pdfs", ROOT / "data" / "index")
    by_path = {Path(d.source_path).name: d for d in docs}

    print("# Generated by scripts/build_corpus.py — do not edit by hand.")
    print("#")
    print("# Public identifiers for the papers the ground truth was written")
    print("# against, so the ablation table can be reproduced from sources a")
    print("# reader can obtain. Entries marked `needs:` were not resolvable")
    print("# from the PDF or its filename and want a human to supply the id —")
    print("# a guessed DOI points at a different paper and looks authoritative.")
    print("\npapers:")

    resolved = unresolved = 0
    for path in sorted((ROOT / "data" / "pdfs").glob("*.pdf")):
        doc = by_path.get(path.name)
        title = (doc.title if doc else path.stem).replace('"', "'")[:110]
        slug = re.sub(r"[^a-z0-9]+", "-", path.stem.lower()).strip("-")[:48]
        ident = _identify(doc, path)
        print(f"  - id: {slug}")
        print(f'    title: "{title}"')
        if ident:
            print(f"    {ident[0]}: \"{ident[1]}\"")
            resolved += 1
        else:
            print('    needs: "public identifier not found — add doi/arxiv/biorxiv by hand"')
            unresolved += 1

    print(f"\n# {resolved} resolved, {unresolved} need a human.", file=sys.stderr)


if __name__ == "__main__":
    main()
